### ISSUE TITLE
Entry of MultiscaleInit when setting l0=0.

### ISSUE THREAD

**Issue by arouwane** [jcpassieux/pyxel#4]
When setting l0=0 as entry in multi-scale initialization, a problem raises because a division by zero happens when using the normalization vector V. 
Is adding an if condition in the end of MultiscaleInit so that the function Correlate is used with l0=None when l0=0 can be viewed as a solution ?  
  if l0==0: 
        U, r = Correlate(f, g, m2, cam2, l0=None, 
                 Basis=Basis, L=L, U0=U, eps=eps, disp=disp)
  else: 
        U, r = Correlate(f, g, m2, cam2, l0=l0 * 2 ** iscale, 
                          Basis=Basis, L=L, U0=U, eps=eps, disp=disp)

**Comment by jcpassieux** [comment]
Thanks. It's been corrected.
