### ISSUE TITLE
Image load 

### ISSUE THREAD

**Issue by maxbut38** [jcpassieux/pyxel#6]
Hi,

When I try to run examples there is a problem for loading images. It says : TypeError: Image.__new__() missing 1 required positional argument: 'height'. 
Is it a problem of incompatibility between pillow and pixel ?

Best regards,

**Comment by arouwane** [comment]
Hi, 
Yes, it is an incompatibility, Pyxel has its own Image object.

**Comment by jcpassieux** [comment]
Exactly, it takes as argument a `pyxel.Image` or a `pyxel.Volume` object, not a `pillow` object.
To convert, you can just do:

`pillow_image = Image.open('toto.tif')`

and then 

```
pyxel_image = px.Image('')
pyxel_image.pix = np.array(pillow_image)
pyxel_image.ToGray()
```
